import styled from 'styled-components';
import img1 from './../static/1.png'
import img2 from './../static/2.png'
import img3 from './../static/3.png'
import img4 from './../static/4.png'

const Container = styled.div`
    height: 600px;
    width: 60%;
    margin-left: 20%;
`;

const ItemContainer = styled.div`
    display: flex;
    height: 250px;
    border-radius: 200px;
    border: 2px solid;
    border-color: #f1eded;
    justify-content: space-between;
`;

const Item = styled.div`
    border-radius: 100px;
    background-color: #151956;
    height: 210px;
    width: 210px;
    margin: 20px;
`;

const P = styled.p`
    font-size: 35px;
    font-weight: 700;
    text-align: center;
`;

const TextTitle = styled.p`
    text-align: center;
    font-size: 30px;
    font-weight: 700;
`;

const TextPara = styled.p`
    text-align: center;
`;

const Mark = styled.mark`
    background-color: transparent;
    color: #63d6d6;
`;

const Img1 = styled.img`
    height: 100px;
    width: 100px;
    margin-top: 50px;
    margin-left: 50px;
    margin-bottom: 80px;
`;

const Img2 = styled.img`
    height: 100px;
    width: 100px;
    margin-top: 50px;
    margin-left: 50px;
    margin-bottom: 80px;
`;

const Img3 = styled.img`
    height: 100px;
    width: 100px;
    margin-top: 50px;
    margin-left: 50px;
    margin-bottom: 80px;
`;

const Img4 = styled.img`
    height: 100px;
    width: 100px;
    margin-top: 50px;
    margin-left: 50px;
    margin-bottom: 80px;
`;

function SubPage3(){
    return (
        <Container>
            
            <P>
                integrate.ai enables <Mark> secure cross-organization 
                data collaboration </Mark>    
                , so you can work on your next breakthrough.
            </P>

            <ItemContainer>
                <Item>
                    <Img1 src={img1}/>
                    <TextTitle>
                        Life Sciences
                    </TextTitle>
                    <TextPara>
                        Access more data across sites to improve 
                        targeted therapeutics, diagnostic accuracy 
                        and patient outcomes.
                    </TextPara>
                </Item>
                <Item>
                    <Img2 src={img2} />
                    <TextTitle>
                        Product Solutions
                    </TextTitle>
                    <TextPara>
                        Enable your customers to generate insights 
                        on distributed data right in your product.
                    </TextPara>
                </Item>
                <Item>
                    <Img3 src={img3} />
                    <TextTitle>
                        Industrial IoT
                    </TextTitle>
                    <TextPara>
                        Create deeper insights across sensitive data 
                        generated by connected machines.
                    </TextPara>
                </Item>
                <Item>
                    <Img4 src={img4} />
                    <TextTitle>
                        Academia
                    </TextTitle>
                    <TextPara>
                        Build stronger data collaborations with 
                        institutions around the world to power 
                        novel research.
                    </TextPara>
                </Item>
            </ItemContainer>

        </Container>
    );
}

export default SubPage3